apiVersion: deployments.plural.sh/v1alpha1
kind: Cluster
metadata:
  name: existing
  namespace: default
spec:
  handle: lukasz
---
apiVersion: deployments.plural.sh/v1alpha1
kind: GitRepository
metadata:
  name: simple-helm
  namespace: default
spec:
  url: https://github.com/zreigz/simple-helm.git
---
apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: helm-app
  namespace: default
spec:
  namespace: helm-app
  name: helm-app
  repositoryRef:
    kind: GitRepository
    name: simple-helm
    namespace: default
  git:
    ref: main
    folder: /
  helm:
    luaScript: |
      values = {}
      valuesFiles = {}
      
      values["replicaCount"] = 1
      
      local files = fs.walk("templates")
      local yamlStr = fs.read("values.yaml")
      local yamlData = encoding.yamlDecode(yamlStr)
      -- Allocate a large table with millions of entries
      local t = {}
      for i = 1, 10^7 do
      t[i] = string.rep("x", 100)  -- 100 bytes per entry, ~1GB total
      end
      
      print("Large table created.")
    
      -- Perform a slow computation: sum of a large range with delay
      local sum = 0
      for i = 1, 10^8 do
      sum = sum + (i % 1000)
      if i % 10000000 == 0 then
      print("Progress:", i)
      end
      end
      
      print("Computation done. Sum =", sum)

  clusterRef:
    name: existing
    namespace: default